### ISSUE TITLE
Support ssh remotes

### ISSUE THREAD

**Issue by AurelienGasser** [Konamiman/BrowseInRemoteGitRepository#2]
Currently only http remotes seem to be supported.

Add support for ssh remotes, such as:

    [remote "origin"]
        url = git@gitlab.stackexchange.com:careers/careers.git
        fetch = +refs/heads/*:refs/remotes/origin/*

**Comment by Konamiman** [comment]
Thanks for reporting! Isn't that covered by the change I made in v1.4?

**Comment by AurelienGasser** [comment]
Looks like it is. I just updated and tried again, and it worked.
Thank you! :)
